name: "Test variables"
on:  
  workflow_dispatch:
    inputs:
      entorno:
        type: environment
        description: "Environment to use"
        default: "int"
    

jobs:
  job1:    
    runs-on: ubuntu-latest
    environment: int
    steps:
      - name: Print  var
        run: echo "The value of VAR_ROLE es ${{vars.VAR_ROLE}} "
       
